sclera_col.<UDIM>: Linear
sclera_rough.<UDIM>: Linear
sclera_disp.<UDIM>: Linear
skin_light_col.<UDIM>: Linear
skin_dark_col.<UDIM>: Linear
skin_cavity_rough_coat.<UDIM>: Linear
skin_disp.<UDIM>: Linear
mouth_col.<UDIM>: Linear
mouth_rough.<UDIM>: Linear
mouth_disp.<UDIM>: Linear
iris_col.<UDIM>: Linear
iris_rough.<UDIM>: Linear
iris_disp.<UDIM>: Linear
age_skin_disp.<UDIM>: Linear
